#!/bin/bash

if [ ! $(command -v singularity) ]; then
	module load singularity
fi

VERSION=2.10
PACKAGE=cutadapt
TOOL=$PACKAGE
DIRECTORY=/opt/packages/$PACKAGE/$VERSION

singularity exec -B /ocean $DIRECTORY/singularity-$PACKAGE-$VERSION.sif $TOOL "$@"
